<?php
return array (
    'getSingleRecipeCollection' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'collectionId' => 'id',
            'resultsPerPage' => 'rpp',
            'pageNumber' => 'pg',
            'test' => 'test',
            'sessionForLogging' => 'sessionForLogging',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/collection/{{collectionId}}',
        'method' => 'GET',
    ),
    'getRecipeCollectionMetadata' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'collectionId' => 'id',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/collection/{{collectionId}}/meta',
        'method' => 'GET',
    ),
    'getRecipeCollections' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'test' => 'test',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/collections',
        'method' => 'GET',
    ),
    'getFoodGlossaryArticleByTerm' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'term' => 'term',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/glossary/byterm/{{term}}',
        'method' => 'GET',
    ),
    'getFoodGlossaryArticle' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'articleId' => 'id',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/glossary/{{articleId}}',
        'method' => 'GET',
    ),
    'deleteItemsFromGroceryList' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/grocerylist',
        'method' => 'DELETE',
    ),
    'getMyGroceryList' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/grocerylist',
        'method' => 'GET',
    ),
    'departmentalizeItemsInGroceryList' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'model' => 'items',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/grocerylist/department',
        'method' => 'POST',
    ),
    'addSingleItemToGroceryList' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'newItemName' => 'name',
            'newItemQuantity' => 'quantity',
            'newItemUnit' => 'unit',
            'newItemNotes' => 'notes',
            'newItemDepartment' => 'department',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/grocerylist/item',
        'method' => 'POST',
    ),
    'deleteItemFromGroceryList' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'guid' => 'guid',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/grocerylist/item/{{guid}}',
        'method' => 'DELETE',
    ),
    'updateGroceryItem' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'requisiteName' => 'name',
            'requisiteQuantity' => 'quantity',
            'requisiteUnit' => 'unit',
            'requisiteNotes' => 'notes',
            'requisiteDepartment' => 'department',
            'guid' => 'guid',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/grocerylist/item/{{guid}}',
        'method' => 'PUT',
    ),
    'addRecipeToGroceryList' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'recipeId',
            'scale' => 'scale',
            'markAsPending' => 'markAsPending',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/grocerylist/recipe',
        'method' => 'POST',
    ),
    'synchronizeGroceryList' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'requisiteItems' => 'req_list_Items',
            'requisiteRecipes' => 'req_list_Recipes',
            'since' => 'since',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/grocerylist/sync',
        'method' => 'POST',
        'custom' => true,
    ),
    'createRecipe' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'title' => 'Title',
            'description' => 'Description',
            'category' => 'Category',
            'subcategory' => 'Subcategory',
            'primaryIngredient' => 'PrimaryIngredient',
            'cuisine' => 'Cuisine',
            'microcategory' => 'Microcategory',
            'starRating' => 'StarRating',
            'imageURL' => 'ImageURL',
            'instructions' => 'Instructions',
            'yieldNumber' => 'YieldNumber',
            'yieldUnit' => 'YieldUnit',
            'totalMinutes' => 'TotalMinutes',
            'activeMinutes' => 'ActiveMinutes',
            'isPrivate' => 'IsPrivate',
            'isBookmark' => 'IsBookmark',
            'bookmarkURL' => 'BookmarkURL',
            'bookmarkSiteLogo' => 'BookmarkSiteLogo',
            'bookmarkImageURL' => 'BookmarkImageURL',
            'isRecipeScan' => 'IsRecipeScan',
            'adTags' => 'AdTags',
            'ingredientsTextBlock' => 'IngredientsTextBlock',
            'allCategoriesText' => 'AllCategoriesText',
            'isSponsored' => 'IsSponsored',
            'collection' => 'Collection',
            'collectionID' => 'CollectionID',
            'adminBoost' => 'AdminBoost',
            'poster' => 'Poster',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe',
        'method' => 'POST',
        'custom' => true,
    ),
    'updateRecipe' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeID' => 'RecipeID',
            'title' => 'Title',
            'description' => 'Description',
            'category' => 'Category',
            'subcategory' => 'Subcategory',
            'primaryIngredient' => 'PrimaryIngredient',
            'cuisine' => 'Cuisine',
            'microcategory' => 'Microcategory',
            'starRating' => 'StarRating',
            'imageURL' => 'ImageURL',
            'instructions' => 'Instructions',
            'yieldNumber' => 'YieldNumber',
            'yieldUnit' => 'YieldUnit',
            'totalMinutes' => 'TotalMinutes',
            'activeMinutes' => 'ActiveMinutes',
            'isPrivate' => 'IsPrivate',
            'isBookmark' => 'IsBookmark',
            'bookmarkURL' => 'BookmarkURL',
            'bookmarkSiteLogo' => 'BookmarkSiteLogo',
            'bookmarkImageURL' => 'BookmarkImageURL',
            'isRecipeScan' => 'IsRecipeScan',
            'adTags' => 'AdTags',
            'ingredientsTextBlock' => 'IngredientsTextBlock',
            'allCategoriesText' => 'AllCategoriesText',
            'isSponsored' => 'IsSponsored',
            'collection' => 'Collection',
            'collectionID' => 'CollectionID',
            'adminBoost' => 'AdminBoost',
            'poster' => 'Poster',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe',
        'method' => 'PUT',
        'custom' => true,
    ),
    'updateRecipeNutritionInfo' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeID' => 'RecipeID',
            'singularYieldUnit' => 'SingularYieldUnit',
            'totalCalories' => 'TotalCalories',
            'totalFat' => 'TotalFat',
            'caloriesFromFat' => 'CaloriesFromFat',
            'totalFatPct' => 'TotalFatPct',
            'satFat' => 'SatFat',
            'satFatPct' => 'SatFatPct',
            'monoFat' => 'MonoFat',
            'polyFat' => 'PolyFat',
            'transFat' => 'TransFat',
            'cholesterol' => 'Cholesterol',
            'cholesterolPct' => 'CholesterolPct',
            'sodium' => 'Sodium',
            'sodiumPct' => 'SodiumPct',
            'potassium' => 'Potassium',
            'potassiumPct' => 'PotassiumPct',
            'totalCarbs' => 'TotalCarbs',
            'totalCarbsPct' => 'TotalCarbsPct',
            'dietaryFiber' => 'DietaryFiber',
            'dietaryFiberPct' => 'DietaryFiberPct',
            'sugar' => 'Sugar',
            'protein' => 'Protein',
            'proteinPct' => 'ProteinPct',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe',
        'method' => 'PUT',
        'custom' => true,
    ),
    'updateRecipeIngredients' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeID' => 'RecipeID',
            'ingredients' => 'Ingredients',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe',
        'method' => 'PUT',
        'custom' => true,
    ),
    'getRecipeAutocomplete' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'query' => 'query',
            'limit' => 'limit',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/autocomplete',
        'method' => 'GET',
    ),
    'getRecipeCategories' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/categories',
        'method' => 'GET',
    ),
    'deleteMyReviewReply' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'replyId' => 'replyId',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/review/replies/{{replyId}}',
        'method' => 'DELETE',
    ),
    'updateMyReviewReply' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'replyId' => 'replyId',
            'data' => 'Comment',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/review/replies/{{replyId}}',
        'method' => 'PUT',
    ),
    'getSingleReview' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'reviewId' => 'reviewId',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/review/{{reviewId}}',
        'method' => 'GET',
    ),
    'updateReview' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'reviewId' => 'reviewId',
            'reviewStarRating' => 'StarRating',
            'reviewMakeAgain' => 'MakeAgain',
            'reviewComment' => 'Comment',
            'reviewActiveMinutes' => 'ActiveMinutes',
            'reviewTotalMinutes' => 'TotalMinutes',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/review/{{reviewId}}',
        'method' => 'PUT',
    ),
    'getReviewReplies' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'reviewId' => 'reviewId',
            'pageNumber' => 'pg',
            'resultsPerPage' => 'rpp',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/review/{{reviewId}}/replies',
        'method' => 'GET',
    ),
    'addReplyToReview' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'reviewId' => 'reviewId',
            'data' => 'Comment',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/review/{{reviewId}}/replies',
        'method' => 'POST',
    ),
    'createRecipeScan' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'test' => 'test',
            'devicetype' => 'devicetype',
            'scanLatitude' => 'lat',
            'scanLongitude' => 'lng',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/scan',
        'method' => 'POST-GET',
    ),
    'deleteMySingleRecipe' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'id',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}',
        'method' => 'DELETE',
    ),
    'getMySingleRecipe' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'id',
            'prefetch' => 'prefetch',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}',
        'method' => 'GET',
    ),
    'createRecipeFeedback' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'recipeId',
            'data' => 'feedback',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}/feedback',
        'method' => 'POST',
    ),
    'addRecipeImage' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'recipeId',
            'caption' => 'caption',
            'imageLatitude' => 'lat',
            'imageLongitude' => 'lng',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}/image',
        'method' => 'POST-GET',
    ),
    'createRecipeNote' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeNote' => 'Notes',
            'recipeNotePeople' => 'People',
            'recipeNoteVariations' => 'Variations',
            'recipeNoteUserID' => 'UserID',
            'recipeId' => 'RecipeID',
            'recipeNoteGUID' => 'GUID',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}/note',
        'method' => 'POST',
    ),
    'deleteRecipeNote' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'recipeId',
            'noteId' => 'noteId',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}/note/{{noteId}}',
        'method' => 'DELETE',
    ),
    'getMySingleRecipeNote' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'recipeId',
            'noteId' => 'noteId',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}/note/{{noteId}}',
        'method' => 'GET',
    ),
    'updateRecipeNote' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'noteId' => 'ID',
            'recipeNoteNotes' => 'Notes',
            'recipeNotePeople' => 'People',
            'recipeNoteVariations' => 'Variations',
            'recipeNoteUserID' => 'UserID',
            'recipeId' => 'RecipeID',
            'recipeNoteGUID' => 'GUID',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}/note/{{noteId}}',
        'method' => 'PUT',
    ),
    'getRecipeNotes' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'rpp',
            'pageNumber' => 'pg',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}/notes',
        'method' => 'GET',
    ),
    'getRecipePhotos' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'rpp',
            'pageNumber' => 'pg',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}/photos',
        'method' => 'GET',
    ),
    'getRelatedRecipes' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'recipeId',
            'pageNumber' => 'pg',
            'resultsPerPage' => 'rpp',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}/related',
        'method' => 'GET',
    ),
    'getMyRecipeReview' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'recipeId',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}/review',
        'method' => 'GET',
    ),
    'createReview' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'recipeId',
            'starRating' => 'StarRating',
            'makeAgain' => 'MakeAgain',
            'comment' => 'Comment',
            'activeMinutes' => 'ActiveMinutes',
            'totalMinutes' => 'TotalMinutes',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}/review',
        'method' => 'POST',
    ),
    'getRecipeReviews' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'recipeId',
            'pageNumber' => 'pg',
            'resultsPerPage' => 'rpp',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}/reviews',
        'method' => 'GET',
    ),
    'getRecipeScanImages' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'recipeId' => 'recipeId',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipe/{{recipeId}}/scans',
        'method' => 'GET',
    ),
    'searchRecipes' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'searchAnywhereByKeyword' => 'any_kw',
            'folder' => 'folder',
            'collectionId' => 'coll',
            'filter' => 'filter',
            'searchInTitleByKeyword' => 'title_kw',
            'userId' => 'userId',
            'username' => 'username',
            'token' => 'token',
            'photos' => 'photos',
            'boostmine' => 'boostmine',
            'includeCategoryId' => 'include_cat',
            'excludeCategoryId' => 'exclude_cat',
            'includePrimaryCat' => 'include_primarycat',
            'includeIngredients' => 'include_ing',
            'excludeIngredients' => 'exclude_ing',
            'cuisine' => 'cuisine',
            'db' => 'db',
            'userset' => 'userset',
            'resultsPerPage' => 'rpp',
            'pageNumber' => 'pg',
            'vegetarian' => 'vtn',
            'vegan' => 'vgn',
            'containsCheese' => 'chs',
            'glutenFree' => 'glf',
            'nutFree' => 'ntf',
            'dairyFree' => 'dyf',
            'seaFoodFree' => 'sff',
            'shellfishFree' => 'slf',
            'treeNutFree' => 'tnf',
            'whiteMeatFree' => 'wmf',
            'redMeatFree' => 'rmf',
            'containsPasta' => 'cps',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipes',
        'method' => 'GET',
    ),
    'getRandomRecipe' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipes/random',
        'method' => 'GET',
    ),
    'getRecipeRaves' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'pageNumber' => 'pg',
            'resultsPerPage' => 'rpp',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipes/raves',
        'method' => 'GET',
    ),
    'getUserRecentlyViewedRecipes' => array (
        'dictionary' => array (
            'apiKey' => 'apiKey',
            'bigovenUsername' => 'bigovenUsername',
            'bigovenPassword' => 'bigovenPassword',
            'pageNumber' => 'pg',
            'resultsPerPage' => 'rpp',
        ),
        'vendorUrl' => 'http://api2.bigoven.com/recipes/recentviews',
        'method' => 'GET',
    ),
);